spring.application.name=backend
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?tcpKeepAlive=true
spring.datasource.username=postgres.jhbqpzwaivcbxzgofjdz
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=0c598c3ece6f8e
spring.mail.password=579ebf6fc974f9
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
supabase.url=${SUPABASE_URL:}
supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:}
supabase.storage.bucket=${SUPABASE_STORAGE_BUCKET:diplomas}
